# Generated by Django 4.2.2 on 2023-07-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_myfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
