# Generated by Django 4.2.2 on 2023-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_delete_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phrases',
            field=models.TextField(blank=True),
        ),
    ]
