# Generated by Django 4.2.2 on 2023-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
