# Generated by Django 4.2.2 on 2023-07-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_userprofile_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='frase_list',
            field=models.TextField(blank=True),
        ),
    ]
