# Generated by Django 4.2.2 on 2023-07-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_preferencias_remove_userprofile_frase_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencias',
            old_name='filme',
            new_name='titulo',
        ),
    ]
