# Generated by Django 4.2.2 on 2023-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_rename_titulo_preferencias_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencias',
            old_name='filme',
            new_name='titulo',
        ),
    ]
