# Generated by Django 4.2.2 on 2023-07-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_rename_filme_preferencias2_livro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferencias',
            new_name='Preferencias_filme',
        ),
        migrations.RenameModel(
            old_name='Preferencias2',
            new_name='Preferencias_livro',
        ),
    ]
