# Generated by Django 4.2.2 on 2023-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_rename_preferencias_preferencias_filme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias_animacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='animacoes_preferidos',
            field=models.ManyToManyField(to='usuarios.preferencias_animacao'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='series_preferidos',
            field=models.ManyToManyField(to='usuarios.preferencias_serie'),
        ),
    ]
