# Generated by Django 4.2.2 on 2023-07-09 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0024_amizade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amigos',
            field=models.ManyToManyField(related_name='amigos+', to=settings.AUTH_USER_MODEL),
        ),
    ]
